export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_QUERIED_MOVIES_SUCCESS = "LOAD_QUERIED_MOVIES_SUCCESS";
export const RESET_QUERIED_MOVIES = "RESET_QUERIED_MOVIES";
export const RESET_LATEST_MOVIES = "RESET_LATEST_MOVIES";
export const SAVE_FAV_MOVIE = "SAVE_FAV_MOVIE";
export const DELETE_FAV_MOVIE = "DELETE_FAV_MOVIE";
export const SAVE_MOVIE_IN_WATCH_LATER_LIST = "SAVE_MOVIE_IN_WATCH_LATER_LIST";
export const LOAD_MORE_MOVIES_SUCCESS = "LOAD_MORE_MOVIES_SUCCESS";
export const DELETE_MOVIE_IN_WATCH_LATER_LIST =
  "DELETE_MOVIE_IN_WATCH_LATER_LIST";
